---
- name: Main playbook
  hosts: deploy_hosts 
  vars:
    remove_nginx: "{{ remove_nginx_package | bool }}"
  tasks:
    - name: Environment variables
      debug:
        var: vars

    - name: Show current user
      shell: id

    - name: Show current user 2
      shell: id
      become: yes

    - name: Host's FQDN
      debug:
        msg: "This is host's FQDN: {{ vars.ansible_fqdn }}"
      

#    - name: Add Nginx repository
#      yum_repository:
#        name: nginx
#        description: nginx repo
#        baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
#        gpgcheck: no
#      when: not remove_nginx
#      become: yes

#    - name: Inastall Nginx
#      yum:
#        name:
#          - nginx
#        state: present
#        enablerepo: nginx
#      when: not remove_nginx
#      become: yes

#    - name: Remove Nginx
#      yum:
#        name:
#          - nginx
#        state: absent
#      when: remove_nginx
#      become: yes

#    - name: Remove repository (and clean up left-over metadata)
#      yum_repository:
#        name:
#          - nginx
#        state: absent
#      notify: yum-clean-metadata
#      when: remove_nginx
#      become: yes
 
#  handlers:
#  # Handler showing how to clean yum metadata cache
#    - name: yum-clean-metadata
#      command: yum clean metadata
#      args:
#        warn: no
#      become: yes

