---
- name: Main playbook
  hosts: deploy_hosts
  become: yes
  vars:
    remove_nginx: '{{ remove_nginx_package | bool }}'
  vars_files:
    - '{{ workspace }}/Ansible/variables/all.yml'
    - '{{ workspace }}/Ansible/inventories/secret.yml'
  tasks:
#    - name: Environment variables
#      debug:
#        var: vars
#      become: no

    - name: Debug variable 'remove_nginx'
      debug:
        msg: "remove_nginx = {{ remove_nginx }}"
      become: no

    - name: Install and setup Nginx
      block:
        - name: Add Nginx repository
          yum_repository:
            name: nginx
            description: nginx repo
            baseurl: https://nginx.org/packages/centos/$releasever/$basearch/
            gpgcheck: no

        - name: Install Nginx
          yum:
            name: nginx
            state: present
            enablerepo: nginx
          notify: restart-nginx

        - name: Prepare Nginx config
          template:
            src: '{{ workspace }}/Ansible/templates/proxy.conf.j2'
            dest: /etc/nginx/conf.d/proxy.conf
            owner: 'root'
            group: 'root'
            mode: '0644'
          notify: restart-nginx
      when: not remove_nginx

    - name: Remove Nginx and Yum repo
      block:
        - name: Remove Nginx
          yum:
            name: nginx
            state: absent

        - name: Remove repository (and clean up left-over metadata)
          yum_repository:
            name: nginx
            state: absent
          notify: yum-clean-metadata
      when: remove_nginx

  handlers:
    - name: restart-nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

    # Handler showing how to clean yum metadata cache
    - name: yum-clean-metadata
      command: yum clean metadata
